# Generated by Django 6.0.5 on 2026-09-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
        ('rooms', '0009_room_faculty_room_full_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('room', 'session_key')},
        ),
    ]
