# Generated by Django 6.0.5 on 2026-05-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='room',
        ),
        migrations.AddField(
            model_name='classsession',
            name='raw_venue_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rooms', to='timetable.classsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rooms', to='rooms.room')),
            ],
            options={
                'unique_together': {('class_session', 'room')},
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='rooms',
            field=models.ManyToManyField(related_name='class_sessions', through='timetable.SessionRoom', to='rooms.room'),
        ),
    ]
