# Generated by Django 6.0.5 on 2026-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_image'),
        ('timetable', '0002_remove_classsession_room_classsession_raw_venue_text_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['semester', 'day_of_week', 'start_time'], name='timetable_c_semeste_73a523_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionroom',
            index=models.Index(fields=['room'], name='timetable_s_room_id_dbeeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionroom',
            index=models.Index(fields=['room', 'class_session'], name='timetable_s_room_id_9eb9b4_idx'),
        ),
    ]
