# Generated by Django 6.0.5 on 2026-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_building_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
