# Generated by Django 6.0.5 on 2026-07-02 11:00

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Building = apps.get_model('rooms', 'Building')
    for room in Room.objects.all():
        if room.slug:
            continue
        building = Building.objects.filter(id=room.building_id).first()
        if building:
            room.slug = slugify(f"{building.code} {room.name}")
        else:
            room.slug = slugify(room.name)
        room.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_has_power_room_image_room_slug'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, reverse_code=migrations.RunPython.noop),
    ]
