# Generated by Django 6.0.5 on 2026-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_regenerate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='faculty',
            field=models.CharField(blank=True, default='Engineering', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='full_name',
            field=models.CharField(blank=True, default='NONE', max_length=255),
        ),
    ]
